#!/bin/csh -f

set nonomatch

foreach dir ( src external )
  if ( -d $dir ) then
    ( cd $dir ; echo $dir ; /bin/rm -f core *.mod *.o *.obj *.inc *.f90 *.a \
                      rsl.* )
  endif
end

set echo
set arg="$1"
if ( "$arg" == '-a' || "$arg" == '-aa' ) then
  if ( -f configure.gen_be ) then
    /bin/cp configure.gen_be configure.gen_be.backup
    /bin/rm -f configure.gen_be
  endif
  ( cd external ; make -i superclean )
  ( cd src ; /bin/rm -f *.exe )
endif

