# *****************************************************************
#  makefile
#
#  Make the summary.x executable. 
#
# *****************************************************************

BINDIR = ../../exec

LIBS   = $(W3NCO_LIB4)

OBJS   = summary.o  avgsdv.o

#
# *****************************************************************
#

CMD = rad_ig_summary.x

all:  $(CMD)

clean:
	rm -f *.o
	rm -f *.mod
	rm -f *.x

check_prereqs:
	/nwprod/spa_util/check_libs.bash $(LIBS)

install:
	cp -f $(CMD) $(BINDIR)/

debug:  FFLAGS = $(D_FFLAGS)
debug:  $(CMD)

$(CMD):         $(OBJS)
	$(CF) $(FFLAGS) $(LDFLAGS) -o $(@) $(OBJS) $(LIBS)


summary.o : summary.f90
	$(CF) $(FFLAGS) -c $(*).f90

avgsdv.o : avgsdv.f90
	$(CF) $(FFLAGS) -c $(*).f90
