      SUBROUTINE ENDMAP(LUNIPK6,NRECFAX)

C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    ENDMAP      WRITE END-OF-ALL-MAPS RECORD ON FAX FILE
C   PRGMMR: HENRICHSEN       ORG: W/NP12     DATE: 1999-07-20
C
C ABSTRACT: TO WRITE THE END-OF-ALL-MAPS RECORD TO THE FAX/VARIAN
C   NMC 6-BIT PACKED FILE.
C   TO WRITE END-OF-ALL-MAPS RECORD TO OUTPUT 6-BIT PACKED FILE
C   ON UNIT=LUNIPK6
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR(S)'S NAME(S) HERE
C   1996-08-13 SHIMOMURA:  IN REWRITE FOR CRAY, 
C                          I REMOVED THE AFOS OPTION; AND
C                          I ADDED THE OUTPUT DSRN TO THE CALL SEQUENCE 
C   1999-07-20 HENRICHSEN  REWRITE TO USE DIRECT ACCESS I/O FOR THE 
C                          IBM SP.
C
C USAGE:    CALL ENDMAP(LUNIPK6,NRECFAX)
C   INPUT ARGUMENT LIST:
C     LUNIPK6  - OUTPUT UNIT NUMBER FOR THE FAX/VARIAN 
C                 NMC 6-BIT PACKED FILE
C     NRECFAX  -  LAST RECORD WRITTEN TO LUNIPK6.    
C
C   OUTPUT FILES:
C              - THE END-OF-ALL-MAPS FLAGGED RECORD IS WRITTEN OUT
C                   TO UNIT=LUNIPK6
C
C REMARKS: 
C   CAUTION:  THE CALL SEQUENCE IS CHANGED FROM OLD ENDMAP() WITH THE
C               ADDED "LUNIPK6"
C
C ATTRIBUTES:
C   LANGUAGE: IBM FORTRAN 90
C   MACHINE:  IBM
C
C$$$

      INTEGER    LUNIPK6
C     IWORK      WORK SPACE FOR 1440-BYTE OUTPUT RECORD
      INTEGER    IWORK(180)    		!... 180 LONGWRDS = 1440 BYTES
      INTEGER    SFL
      DATA       SFL   / Z'FFFFFC0000000000' /
      CHARACTER(1440)  CHARWORK
      EQUIVALENCE (CHARWORK,IWORK)
      
      LUNIT = LUNIPK6
      IF(LUNIPK6 .LE. 0 .OR. LUNIPK6 .GT.99) THEN
C       ... BAD VALUE OF OUTPUT UNIT ...  DO NOTHING
        GO TO 999
      ENDIF

      DO  I = 1,180
        IWORK(I) = 0
      ENDDO

      IWORK(1) = SFL
      
C      WHERE EACH FAX RECORD IS 1440 BYTES

          NRECFAX  = NRECFAX + 1
           WRITE(LUNIPK6, REC=NRECFAX,ERR=999 )CHARWORK

C     ...WHICH WRITES 1440 BYTES ...

  999 CONTINUE
      RETURN
      END
