#!/bin/ksh
set -x

if [ $# -lt 2 ] ; then
 echo "Usage : $0 model_or_experiment_name  yyyymmddhh"
 exit
fi

#
#  This script is to run grid2grid Fortran executable grid2grid.x
#  input: user.ctl.$model which was generated by prepg2g.sh
#

model=`echo $1 |tr "[a-z]" "[A-Z]" `
mdlname=$1
YYYYMMDDHH=$2

cp $exe/regions $work
cp $exe/grid#104 $work
cd $work

#  arange forecast and observation grib file names ############################
# mv fcst.grib.$model fcst.grib
# mv fcst.indx.$model fcst.indx
# mv obsv.grib.$model obsv.grib
# mv obsv.indx.$model obsv.indx

 #### following are just for tendency:
# if [ -s fcst03.grib.$model ] ; then
#  mv fcst03.grib.$model fcst03.grib
#  mv fcst03.indx.$model fcst03.indx
#  mv obsv03.grib.$model obsv03.grib
#  mv obsv03.indx.$model obsv03.indx
# fi

# if [ -s fcst06.grib.$model ] ; then
#  mv fcst06.grib.$model fcst06.grib
#  mv fcst06.indx.$model fcst06.indx
#  mv obsv06.grib.$model obsv06.grib
#  mv obsv06.indx.$model obsv06.indx
# fi

# if [ -s fcst12.grib.$model ] ; then
#  mv fcst12.grib.$model fcst12.grib
#  mv fcst12.indx.$model fcst12.indx
#  mv obsv12.grib.$model obsv12.grib
#  mv obsv12.indx.$model obsv12.indx   
# fi
  
# if [ -s fcst24.grib.$model ] ; then
#  mv fcst24.grib.$model fcst24.grib
#  mv fcst24.indx.$model fcst24.indx
#  mv obsv24.grib.$model obsv24.grib
#  mv obsv24.indx.$model obsv24.indx
# fi
 

# run grid2grid.x executable ##############################################                                                                                                                                                             
$exe/grid2grid.x < g2g.ctl.$model > output.$model
 if [ -s ${mdlname}_${YYYYMMDDHH}.vsdb ] ; then
  cat grid2grid.vsdb >> ${mdlname}_${YYYYMMDDHH}.vsdb
  rm -f grid2grid.vsdb
 else
  mv grid2grid.vsdb ${mdlname}_${YYYYMMDDHH}.vsdb
 fi

# rm -f *.grib fcst.grib.$model
# rm -f  fcst.indx.$model
# rm -f  fcst.indx

 mkdir -p $savedir
 DATE=`echo $YYYYMMDDHH |cut -c 1-8 `
 cp ${mdlname}_${YYYYMMDDHH}.vsdb ${savedir}/${mdlname}_${DATE}.vsdb

exit
