#!/bin/sh

###################################################################
#  Note:  Gmon/parm/gmon.ver file must be sourced before this file
###################################################################
export MY_MACHINE=${MY_MACHINE:-wcoss}

export MY_GMON=/gpfs/td2/emc/da/noscrub/Edward.Safford/Gmon_461/util/Gnorm_Monitor

export HOMEgdasgmon=${MY_GMON}/nwprod/gdas_gmon.v${gdas_gmon_ver}
export HOMEgmon=${MY_GMON}/nwprod/gmon_shared.v${gmon_shared_ver}

export envir=prod
export DATA_IN=/stmpp1/${LOGNAME}/gmon 		# working directory

export LOGdir=/ptmpp1/${LOGNAME}/logs

export TANKverf=/u/Edward.Safford/nbns		# storage directory


#
#  Utilities used by the GMon package
#
export NCP=${NCP:-"/bin/cp -f"}
export Z=${Z:-"gz"}

if [[ $MY_MACHINE = "wcoss" ]]; then
   shell=sh
   . /usrx/local/Modules/default/init/${shell}
   module load lsf

   export SUB="bsub"
   export NWPROD=/nwprod
   export COMPRESS=/usrx/local/bin/pigz
   export UNCOMPRESS="/usrx/local/bin/unpigz -f"

else    # zeus 
   shell=sh
   /usr/bin/modulecmd $shell load ncep

   export SUB=/apps/torque/default/bin/qsub
   export NWPROD=/scratch1/portfolios/NCEPDEV/da/save/Michael.Lueken/nwprod
   export COMPRESS=gzip
   export UNCOMPRESS="gunzip -f"
fi

export NDATE=${NWPROD}/util/exec/ndate
