#!/bin/sh
#------------------------------------------------------------------------------
#
#  GMon_user_settings
#
#  Modify this file in order to change behavior of the GMon package 
#------------------------------------------------------------------------------
#
#  ACCOUNT is used on zeus only for use with the qsub -a flag.  It is
#  empty on other platforms.
#
export ACCOUNT=${ACCOUNT:-}

#
#  PROJECT is used on wcoss only with the bjob -P flag.  It is 
#  empty on other platforms.
#
export PROJECT=${PROJECT:-GDAS-T2O}

#
#  JOB_QUEUE is used on wcoss only with the bjob -q flag.  It is 
#  empty on other platforms.
#
export JOB_QUEUE=${JOB_QUEUE:-dev_shared}

#
#  RUN_ONLY_ON_DEV  1 = dev machine only, 0 = run anywhere
#
export RUN_ONLY_ON_DEV=${RUN_ONLY_ON_DEV:-1}

