      SUBROUTINE IJ2UORV(XRELST,YRELST,XUOR,YUOR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    IJ2UORV     CONVERT GRID COORDINATES TO UORS.
C   PRGMMR: KRISHNA KUMAR         ORG: W/NP12    DATE: 1999-07-01
C
C ABSTRACT: CONVERT GRID COORDINATES FROM NMC STD GRID RELATIVE
C   TO THE POLE, TO UNITS OF RESOLUTION (UOR) ON THE 1:10,000,000
C   POLAR STEREO GRAPHIC MAP, LIKE NORAMPO,
C   WHICH IS USING WORKING UNITS TO THE 1/1000TH OF CM.
C   LOGIC GETS THERE VIA LFM GRID RELATIVE TO THE POLE.
C   NMC STANDARD GRID IS ORIENTED AT 80W, THE STANDARD GRID INTERVAL
C   IS 381 KM. THE LFM FRID IS ORIENTED AT 105W, AND HAS A GRID
C   INTERVAL OF 190.5 KM.
C
C PROGRAM HISTORY LOG:
C   89-05-08  ORIGINAL AUTHOR SHIMOMURA
C   94-12-22  LUKE LIN      CONVERT IT TO CFT-77.
C   96-08-28  LUKE LIN      MODIFY FOR LFM BACKGROUND FROM AVN MODEL
C   96-09-11  LUKE LIN      MODIFY FOR NGM CGRID MAP.
C 1999-07-01  KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY 
C                           TO IBM RS/6000
C
C USAGE     CALL IJ2UORV(XRELST,YRELST,XUOR,YUOR)
C   INPUT ARGUMENT LIST:
C     XRELST   - REAL*4 THE X GRID COORDINATES FROM NMC STD GRID
C              - RELATIVE TO THE POLE
C     YRELST   - REAL*4 THE Y GRID COORDINATES FROM NMC STD GRID
C              - RELATIVE TO THE POLE
C     XPOL     - REAL*4 X LOCATAION OF POLE FROM COMMON /POLE/
C     YPOL     - REAL*4 Y LOCATAION OF POLE FROM COMMON /POLE/
C     GDTYPE   - INTEGER*4 GRID TYPE NUMBER FROM COMMON /POLE/
C              - = 05 THEN THIS IS LFM 53X57 ANALSYS GRID.
C              - = 26 THEN THIS IS LFM 53X45 GRID.
C              - = 27 THEN THIS IS STANDARD NMC 65X65 GRID.
C
C   OUTPUT ARGUMENT LIST:
C     XUOR     - REAL*4 X LOCATION IN UORS.
C     YUOR     - REAL*4 Y LOCATION IN UORS.
C
C   OUTPUT FILES:
C     FT06F001 - PRINT FILE.
C
C REMARKS: ONLY TWO GRID TYPES ARE ALLOWED: 26 AND 27.
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
      COMMON  /POLE/ XPOL,YPOL,GDTYPE
      INTEGER      GDTYPE
C
C     ...THE POLE POSITION OF THE GRID(65,65) IS AT GRID(33,33).
C     ...THE POLE POSITION OF THE LFM GRID(53,45) IS AT GRID(27,49).
C
C
C      .... THIS SET IS FOR UOR_DOT
       COMMON /UOR2D/ UGRIDT1,UXPO,UYPO,UXADJUS,UYADJUS,UCU2GI,UORFG,
     1                IP,IPOPT
       REAL     UGRIDT1,UXPO,UYPO,UXADJUS,UYADJUS,UCU2GI
       LOGICAL  UORFG
C
C
      COMMON / ILCON / MAP(15)
      INTEGER       MAP
C
       integer       iacc
       character*8   cacc
       equivalence  (iacc,cacc)
C
C
       REAL    XRELST,YRELST
       REAL    XUOR,YUOR
       REAL    XRELFM,YRELFM
C
       REAL    SINANG
C      ... SINANG = SIND(25.0)
       REAL    COSANG
C      ... COSANG = COSD(25.0)
       REAL    AMULT1
       REAL    AMULT
C      ... WHERE AMULT = 381.0 / 190.5
       REAL    CONVUOR
       REAL    CONVUORNH
       REAL    UOR101
       REAL    UOR104
C
       DATA    SINANG / 0.4226182 /
       DATA    COSANG / 0.9063077 /
C      DATA    SINANG / 0.0000000 /
C      DATA    COSANG / 1.0000000 /
       DATA    AMULT / 2.0 /
       DATA    AMULT1 / 1.0 /
       DATA    CONVUOR / 1905.0 /
       DATA    CONVUORNH / 3810.0 /
C
       DATA    UOR101 /  914.52 /
       DATA    UOR104 /  907.5464 /
C
       IACC = MAP(1)
C       PRINT *,' BACKGROUND=',CACC
C       PRINT *,' GDTYPE =',GDTYPE
C
       IF (GDTYPE .EQ. 27 .OR. GDTYPE .EQ. 28) THEN
C
C         THIS WAS THE STANDARD N.H. 65X65 GRID.
C
C        IF (CACC(1:6) .EQ. 'NH4004') THEN
C           .... GET A NH BACKGROUND
C           WRITE(6,235)XRELST,YRELST,XRELFM,YRELFM
C 235       FORMAT(1H ,'RELROTA X,Y=',2F11.4';   XRLFM,YRLFM=',2F11.4)
         IF (UORFG .AND. UXPO.EQ.65 .AND. UYPO.EQ.65) THEN
            XUOR = XRELST * CONVUOR
            YUOR = YRELST * CONVUOR
         ELSE
            XUOR = XRELST * CONVUORNH
            YUOR = YRELST * CONVUORNH
         ENDIF
C        ELSE IF (CACC(1:6) .EQ. 'NH2005') THEN
C            .... GET A LFM GRID BACKGROUND
C         CALL REROTA(XRELST,YRELST,SINANG,COSANG,AMULT1,XRELFM,YRELFM)
C         XUOR = XRELFM * CONVUOR
C         YUOR = YRELFM * CONVUOR
C        ENDIF
C
       ELSE IF (GDTYPE .EQ. 26 .OR. GDTYPE.EQ.05) THEN
C
C         THIS WAS AN LFM GRID TYPE 53X45
C             OR
C         AN LFM GRID TYPE 53X57
C
          XUOR = XRELST * CONVUOR
          YUOR = YRELST * CONVUOR

       ELSE IF (GDTYPE .EQ. 101) THEN
C
C         THIS WAS A NGM C-GRID 113X91
C
          XUOR = XRELST * UOR101
          YUOR = YRELST * UOR101
       ELSE IF (GDTYPE .EQ. 104) THEN
C
C         THIS WAS A SUPER NGM C-GRID 147X110
C
          XUOR = XRELST * UOR104
          YUOR = YRELST * UOR104
       ELSE
          WRITE(6,FMT='('' IJ2UORV: ERROR '',I3,'' IS A NON VALID'',
     1       '' GRID TYPE.'')')GDTYPE
       ENDIF
       RETURN
       END
