      SUBROUTINE PLTVEC(XP,YP,NMAX,IRETUR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PLTVEC      PLOT VECTORS
C   PRGMMR: KRISHNA KUMAR      ORG: W/NP12   DATE: 1999-07-01
C
C ABSTRACT: PLOT VECTORS
C
C PROGRAM HISTORY LOG:
C   94-09-15  LUKE LIN
C   94-12-30  LUKE LIN      CONVERT IT CFT-77.
C   95-09-30  LUKE LIN      ADD LINE ATTRIBUTES
C   96-07-09  LUKE LIN      CALL IJ2UORV INSTEAD OF IJ2UOR
C 1999-07-01  KRISHNA KUMAR CONVERTED FROM CRAY TO IBM RS/6000
C
C USAGE:    CALL PLTVEC(XP,YP,NMAX,IRETUR)
C   INPUT ARGUMENT LIST:
C     XP       - REAL*4 XP(4000)
C     YP       - REAL*4 XP(4000)
C     NMAX     - THE NUMBER OF COMPLEX INCREMENT DONE
C
C   OUTPUT ARGUMENT LIST:
C     IRETUR   - REUTRN CONDITION
C              - =0, NORMAL
C              - =5, FATAL ERR -- NOT ENOUGH WORKING BUFFER FOR OUT-DGN
C              - =933, NONFATAL ERR -- ATTEMP TO ADD BAD ELEMENT TO DGN
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
      COMMON /MUTCON/ KEYIDX,UA1V,UA2V,UA3V,UM1V,UM2V,UM3V,LINEVU,LINEP,
     X               IGRIDP,T1
C     ...KEY TYPE INDEX, CONSTANT, AND CONTOUR LINE VALUE
C
      REAL      XP(NMAX)
      REAL      YP(NMAX)
      INTEGER   NMAX
C
      COMMON   /ROTAT/ XROT,YROT
C
      COMMON  /POLE/ XPOL,YPOL,GDTYPE
      INTEGER      GDTYPE
C     ...THE POLE POSITION IN GRID(65,65) IS AT GRID(33,33).
C     ...THE POLE POSITION IN GRID(53,45) IS AT GRID(27,49).
C
      COMMON / LNATTR / LNWEIGHT, LNSTYLE, LNCOLOR
      INTEGER      LNWEIGHT
      INTEGER      LNSTYLE
      INTEGER      LNCOLOR
C
C
       CHARACTER*1  NULL
C
       INTEGER      IRC, LEVEL
       INTEGER      I2DUMY
C
       INTEGER      GG(2)
C
       INTEGER      ISPEC(5)
C
       INTEGER      IUORS(360)
C
       DATA         MXNODE /  96 /
       DATA         DIMBIN / 192 /
C
       DATA         GG       / 0,0 /
C
C      . . .   S T A R T   . . .
C
       NULL = CHAR(0)
       IRETUR = 0
       IF (NMAX .LE. 1) RETURN
C
       DO  I =1,5
         ISPEC(I) = 0
       ENDDO
C
       LEVEL =  1
C
C      ... CLASS=0 FOR PRIMARY ELEMENT;
C               =1 FOR PATTERN COMPONENT;
C               =2 FOR CONSTRUCTION ELEMENT;
C               =3 FOR DIMENSION ELEMENT;
C               =4 FOR PRIMARY RULE ELEMENT;
C               =5 FOR LINEAR PATTERNED ELEMENT;
C               =6 FOR CONSTRUCTION RULE ELEMENT.
       ICLASS = 1
       ISPEC(1) = ICLASS
C
       ISPEC(5) = LNCOLOR
C
       ISPEC(4) = LNWEIGHT
C
       ISPEC(3) = LNSTYLE
C
       NODES = 0
C
C      DO  I = 1,100
C        IUORS(I) = 0
C      ENDDO
C
       IREMAN = NMAX
       IPTR = 0
C
   20  CONTINUE
C
       ITODO = 0
       IF (IREMAN .GT. MXNODE) THEN
C          PRINT *,' ****** A LARGE CONTOUR ',NMAX,IREMAN
           ITODO = MXNODE + 1
       ELSE IF (IREMAN .LE. MXNODE) THEN
           ITODO = IREMAN
C          PRINT *, '  OUTPUT A LAST  CONTOUR ', NMAX, IREMAN
       ELSE IF (IREMAN .LE. 0) THEN
C          PRINT *, ' SOMETHING WRONG TO THE IREMAN=',IREMAN
           RETURN
       ENDIF
C
         DO 50 I=IPTR+1,IPTR+ITODO
             XX=XP(I)
             YY=YP(I)
             XX = XX - XPOL
             YY = YY - YPOL
             CALL IJ2UORV(XX,YY,XUOR,YUOR)
             IUORS(2*(I-IPTR) -1) = XUOR
             IUORS(2*(I-IPTR)) = YUOR
   50    CONTINUE
C
       LVALU = (LINEVU + UA3V) * UM3V * 100
       IF (ITODO .EQ. 2) THEN
          CALL LNDFPZ(GG,LEVEL,ISPEC,IUORS,IRETUR,I2DUMY)
C         PRINT *, ' GET A LINE STRING '
       ELSE IF (ITODO .GT. 2) THEN
          CALL LSDFPZ(GG,LEVEL,ISPEC,IUORS,ITODO,IRETUR,I2DUMY,LVALU)
C????     CALL LSDFPI(GG,LEVEL,ISPEC,IUORS,ITODO,IRETUR,I2DUMY)
C???      CALL CUDFPI(GG,LEVEL,ISPEC,IUORS,ITODO,IRETUR,I2DUMY)
       ENDIF
C      PRINT *,' RETURN FROM LSDFPI - IERR=',IRETUR
C
       IREMAN = IREMAN - MXNODE
       IPTR = IPTR + MXNODE
       IF (IREMAN .GT. 0) GO TO 20
      RETURN
      END
