       SUBROUTINE REROTA(X,Y,SINANG,COSANG,AMULT,XSTAR,YSTAR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    REROTA      CONVERT GRID COORDINATES TO UORS.
C   PRGMMR: KRISHNA KUMAR       ORG: W/NP12  DATE: 1999-07-01
C
C ABSTRACT: APPLY THE ROTATION EQUATION OF COORDINATE TRANSFORMATION
C   TO THE STANDARD NMC GRID RELATIVE TO THE POLE.
C
C PROGRAM HISTORY LOG:
C   89-05-08  ORIGINAL AUTHOR SHIMOMURA
C   94-12-30  LUKE LIN        CONVERT IT TO CFT-77
C 1999-07-01  KRISHNA KUMAR   CONVERTED THIS CODE FROM CRAY TO
C                             IBM RS/6000
C
C USAGE     CALL REROTA(X,Y,SINANG,COSANG,AMULT,XSTAR,YSTAR)
C   INPUT ARGUMENT LIST:
C     X        - REAL*4 THE X GRID COORDINATE OF POINT LIKE ON
C              - THE NMC STANDARD GRID RELATIVE TO THE POLE.
C     Y        - REAL*4 THE Y GRID COORDINATE OF POINT LIKE ON
C              - THE NMC STANDARD GRID RELATIVE TO THE POLE.
C     SINANG   - REAL*4 SINE OF THE ANGEL OF ROTATION, WHERE ANGLE OF
C              - ROTATION FOR NMC STD GRID TO LFM WOULD BE 25 DEGREES
C     COSINE   - REAL*4 COSINE OF THE ANGEL OF ROTATION, WHERE ANGLE OF
C              - ROTATION FOR NMC STD GRID TO LFM WOULD BE 25 DEGREES
C     AMULT    - REAL*4 MULTIPLICATIVE FACTOR TO APPLY TO THE GIVEN
C              - GRID INTERVALS TO GET UNITS OF DESIRED STAR GRID:
C              - LIKE AMULT=2.0, THE RATIO OF ORIGIONAL STANDARD
C              - GRID INTERVAL TO DESIRED LFM INTERVAL.
C
C   OUTPUT ARGUMENT LIST:
C     XSTAR    - REAL*4 RESULTING X COORDINATE IN THE DESTINATION GRID
C              - (RELATIVE TO THE POLE)
C     YSTAR    - REAL*4 RESULTING Y COORDINATE IN THE DESTINATION GRID
C              - (RELATIVE TO THE POLE)
C
C   OUTPUT FILES:
C     FT06F001 - PRINT FILE.
C
C REMARKS: DOES NOT CHECK VALIDITY OF GIVEN ARGS, SO BE CAREFUL
C   THE REASON FOR PUTTING THE SINE AND COSINE IN THE ARG
C   IS BECAUSE THIS WILL BE USED ON ENTIRE ARRAYS OF GRIDPOINTS
C   WITH CONSTANT ANGLE, SO THE CONSTANT IS PASSED.
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
       REAL    AMULT
       REAL    COSANG
       REAL    SINANG
       REAL    TINY
       REAL    XSTAR
       REAL    X
       REAL    YSTAR
       REAL    Y
C
       DATA    TINY / 0.000001 /
C
       XSTAR = 0.0
       YSTAR = 0.0
       BMULT = AMULT
       IF(ABS(BMULT) .LT. TINY) BMULT = 1.0
       XPRIME = BMULT * X
       YPRIME = BMULT * Y
       XSTAR = COSANG*XPRIME - SINANG*YPRIME
       YSTAR = SINANG*XPRIME + COSANG*YPRIME
       RETURN
       END
