      SUBROUTINE SWABYT(NOWORD, INARAY, OUARAY)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    SWABYT      SWAP THE BYTES FOR EACH 2-BYTE INTEGER.
C   PRGMMR: KRISHNA KUMAR      ORG: W/NP12    DATE: 1999-07-01
C
C ABSTRACT: SWAP THE BYTE ORDER FOR EACH 2-BYTE INTEGER FROM INPUT
C   ARRAY AND WRITE OUT TO OUTPUT ARRAY.
C
C PROGRAM HISTORY LOG:
C   94-03-30  ORIGINAL AUTHOR   -- LUKELIN
C   94-12-21  LUKE LIN       CONVERT IT CFT-77.
C   95-02-10  LUKE LIN       MODIFY SWAPPING BYTES LOGIC.
C 1999-07-01  KRISHNA KUMAR  CONVERTED THIS CODE FROM CRAY TO
C                            IBM RS/6000
C
C USAGE:    CALL SWABYE(NOWORD, INARAY, OUARAY)
C   INPUT ARGUMENT LIST:
C     NOWORD   - NUMBER WORDS OF INPUT ARRAY.
C     INARAY   - I*8  INARAY(NOWORD) .. INPUT ARRAY.
C
C   OUTPUT ARGUMENT LIST:
C     OUARAY   - I*8  ONLY 2-BYTE OUARAY(NOWORD) .. OUTPUT ARRAY.
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
      INTEGER       NOWORD
      INTEGER*8     INARAY(NOWORD)
      INTEGER       OUARAY(4*NOWORD)
      INTEGER       I2BUFIN(4*NOWORD)
C
      INTEGER       ITEMP,IBYTEL,IBYTER
      INTEGER       MSK0F
      INTEGER       MSKF0
C
      DATA          MSK0F   / Z'000000FF' /
      DATA          MSKF0   / Z'0000FF00' /
C      ...... SUBPROGRAM STARTS ....
      NO2BYTE = NOWORD * 4
      CALL GBYTES(INARAY, I2BUFIN, 0, 16, 0, NOWORD)
C     .... UNPACK 8-BYTE WORD TO 2 BYTES WORD
      DO 100 I=1, NOWORD
         ITEMP = I2BUFIN(I)
         IBYTEL = IAND(MSK0F,ISHFT(ITEMP,-8))
C        .... THE LEFT BYTE BECOMES RIGHT
         IBYTER = IAND(MSKF0,ISHFT(ITEMP, 8))
C        .... THE RIGHT BYTE BECOMES LEFT
         OUARAY(I) = IOR(IBYTER,IBYTEL)
  100 CONTINUE
      RETURN
      END
