#!/bin/sh
###########################################################
# GFS Minimization Monitor (MinMon) job
###########################################################
set -xa
echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export COMPONENT=${COMPONENT:-atmos}


###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA


########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export MINMON_SUFFIX=${MINMON_SUFFIX:-GFS}
export m_job=${m_job:-${MINMON_SUFFIX}_mmDE}


##############################################
# Specify Package Areas
##############################################
export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}
#export PARMmon=${PARMmon:-$HOMEgfs/parm/mon}
export SCRgfs=${SCRgfs:-$HOMEgfs/scripts}
export M_FIXgfs=${M_FIXgfs:-$HOMEgfs/fix/product}

export HOMEminmon=${HOMEminmon:-${HOMEgfs}}
export EXECminmon=${EXECminmon:-$HOMEminmon/exec}
export USHminmon=${USHminmon:-$HOMEminmon/ush}

###################################
# source the parm file
###################################
#.  ${PARMmon}/da_mon.parm


#############################################
# Run setpdy and initialize PDY variables
#############################################
if [[ $MY_MACHINE != "hera" ]]; then
   export cycle=t${cyc}z
   setpdy.sh
   . ./PDY
fi

#############################################
#  determine PDY and cyc for previous cycle
#############################################

cdate=`${NDATE} -6 ${PDY}${cyc}`
echo 'pdate = ${pdate}'

export P_PDY=`echo ${cdate} | cut -c1-8`
export p_cyc=`echo ${cdate} | cut -c9-10`


#############################################
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
TANK_USE_RUN=${TANK_USE_RUN:-1}

export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}

M_TANKverf=${M_TANKverf:-${COM_IN}}
M_TANKverfM0=${M_TANKverfM0:-${M_TANKverf}/${RUN}.${PDY}/${cyc}/$COMPONENT/minmon}
export M_TANKverfM1=${M_TANKverfM1:-${M_TANKverf}/${RUN}.${P_PDY}/${p_cyc}/$COMPONENT/minmon}
export M_TANKverf=$M_TANKverfM0

export COMIN=${COMIN:-$COM_IN/${RUN}.${PDY}/${cyc}/$COMPONENT}

mkdir -p -m 775 $M_TANKverf
 

########################################
# Set necessary environment variables
########################################
export CYCLE_INTERVAL=6
export gsistat=${gsistat:-${COMIN}/gfs.t${cyc}z.gsistat}


########################################################
# Execute the script.
${GMONSH:-$SCRgfs/exgfs_atmos_vminmon.sh} ${PDY} ${cyc}
err=$?
[[ $err -ne 0 ]] && exit $err


################################
# Remove the Working Directory
################################
KEEPDATA=${KEEPDATA:-NO}
cd ${DATAROOT}

if [ ${KEEPDATA} = NO ] ; then
  rm -rf ${DATA}
fi


