<div class='bannerContainer'><img usemap='#STARBanner' id='STARBanner' 
	src='images/banner/Banner_950_links.jpg' 
	alt='NOAA Center for Satellite Applications and Research banner' 
	title='NOAA Center for Satellite Applications and Research'>
	<?php // govt. shutdown notice commented out 10-17-2013 <div style='background-color: #f6dadf; padding: 10px;'>
	// <h3 style='margin: 2px 0px; color: #f40101;'>Federal Government Shutdown Notice</h3><p style='padding: 1px; margin: 0px;'><strong>October 1, 2013</strong> - Due to the Federal Government shutdown, NOAA.gov and most associated 
	// web sites are unavailable. This site will remain accessible during the federal government shutdown. However, information
	// on the site may not be up to date and we may not be able to respond to inquiries until appropriations are enacted.</p></div> ?>
</div>
	<map name='STARBanner'>
		<area shape='rect' coords='0,15,224,84' href='http://www.noaa.gov' alt='National Oceanographic & Atmospheric Administration website' title='National Oceanographic & Atmospheric Administration website'>
		<area shape='rect' coords='224,24,735,80' href='http://www.star.nesdis.noaa.gov/star/index.php' alt='NOAA Center for Satellite Applications and Research website' title='NOAA Center for Satellite Applications and Research website'>
		<area shape='rect' coords='678,84,735,109' href='http://www.star.nesdis.noaa.gov/star/careers.php' alt='STAR Careers' title='Careers'>
		<area shape='rect' coords='735,84,792,109' href='https://www.star.nesdis.noaa.gov/intranet/index.php' alt='STAR Intranet' title='Intranet'><area shape='rect' coords='792,84,850,109' href='http://www.star.nesdis.noaa.gov/star/contact.php' alt='STAR Contact Us' title='Contact Us'>
		<area shape='rect' coords='850,84,950,109' href='#skipTarget' alt='skip navigation link' title='skip navigation links, go to main content'>
	</map>
<table id="mainTable" cellpadding="0" cellspacing="0" border="0"
	summary="this table is for page layout purposes only, not tabular data">