		<h4 id="disclaimer">Data and images displayed on STAR's site 
		are provided for experimental use only and are
		not official operational NOAA products. 
		&nbsp;<a href="http://www.star.nesdis.noaa.gov/star/productdisclaimer.php">More information>></a></h4>
		
		<h3 style="margin-left: 5px; font-size: 1.1em;"><a href="http://www.ospo.noaa.gov/Products/atmosphere/mirs/index.html">MIRS Operational Page</a></h3>
		<h3 style="margin-left: 5px; font-size: 1.1em;"><a href="http://www.star.nesdis.noaa.gov/corp/scsb/mspps/">MSPPS Page</a></h3>
