			<div class="leftNav">
				<ul>
					<li id="index"><a href="index.php">Home</a>
						<ul class="detailContainer">
							<li id="objectives"><a href="objectives.php">Objectives</a></li>
							<li id="background"><a href="background.php">Background</a></li>
							<li id="personnel"><a href="personnel.php">Personnel</a></li>
							<li id="acronyms"><a href="http://www.star.nesdis.noaa.gov/star/acronyms.php"
							     title="this link opens a new window"
							     target="_blank">Acronyms</a>
							</li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="instruments"><a href="instruments.php">Instrument Descriptions</a>
						<ul class="detailContainer">
							<li id="amsua"><a href="amsua.php">AMSUA</a></li>
							<li id="amsub"><a href="amsub.php">AMSUB</a></li>
							<li id="mhs"><a href="mhs.php">MHS</a></li>
							<li id="ssmi"><a href="ssmi.php">SSM/I</a></li>
							<li id="ssmis"><a href="ssmis.php">SSMI/S</a></li>
							<li id="windsat"><a href="windsat.php">Windsat</a></li>
							<li id="amsre"><a href="amsre.php">AMSR-E</a></li>
							<li id="amsr2"><a href="amsr2.php">AMSR2</a></li>
							<li id="snppatms"><a href="snppatms.php">SNPP ATMS</a></li>
							<li id="trmmtmi"><a href="trmmtmi.php">TRMM TMI</a></li>
							<li id="gpmgmi"><a href="gpmgmi.php">GPM GMI</a></li>
							<li id="madras"><a href="madras.php">Megha-Tropiques MADRAS</a></li>
							<li id="saphir"><a href="saphir.php">Megha-Tropiques SAPHIR</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="algorithm"><a href="algorithm.php">Algorithm</a>
						<ul class="detailContainer">
							<li id="mathematical"><a href="mathematical.php">Mathematical Background</a></li>
							<li id="validityspace"><a href="validityspace.php">Validity Space</a></li>
							<li id="onedvar"><a href="onedvar.php">1DVAR vs Regression</a></li>
							<li id="retrieval"><a href="retrieval.php">Simultaneous Retrieval</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="testbed"><a href="testbed.php">Testbed</a>
						<ul class="detailContainer">
							<li id="radianceprocess"><a href="radianceprocess.php">Radiance Process</a></li>
							<li id="inversionprocess"><a href="inversionprocess.php">Inversion Process</a></li>
							<li id="advancedretrieval"><a href="advancedretrieval.php">Advanced Retrieval</a></li>
							<li id="vipp"><a href="vipp.php">VIPP</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="products"><a href="products.php">Product Monitoring</a>
						<ul class="detailContainer">
							<li id="product"><a href="product.php">Daily Products - Low Res.</a></li>
							<li id="highresolution"><a href="highresolution.php">Daily Products - High Res.</a></li>
							<li id="vertical"><a href="vertical.php">Vertical Cross Section</a></li>
							<li id="dataquality"><a href="dataquality.php">Data Quality</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="climates"><a href="climates.php">Climate Monitoring</a>
						<ul class="detailContainer">
							<li id="daily"><a href="daily.php">Daily Maps</a></li>
							<li id="comp"><a href="comp.php">Composite Maps</a></li>
							<li id="climate"><a href="climate.php">Pentad&nbsp;&amp;&nbsp;Monthly Maps</a></li>
							<li id="climate_timeseries"><a href="climate_timeseries.php">Climate Time Series</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="sensorsquality"><a href="sensorsquality.php">Sensor Quality</a>
						<ul class="detailContainer">
							<li id="nedt"><a href="nedt.php">NEDT Monitoring</a></li>
							<li id="fm"><a href="fm.php">Footprint Matching Quality</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="radiomonitoring"><a href="radiomonitoring.php">Radiometric Performance</a>
						<ul class="detailContainer">
							<li id="radio"><a href="radio.php">TB Comparison</a></li>
							<li id="radiobias"><a href="radiobias.php">Calibration Bias Monitoring</a></li>
							<li id="qcradio"><a href="qcradio.php">Performance Tables</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="simulatedmonitoring"><a href="simulatedmonitoring.php">Simulated Performance</a>
						<ul class="detailContainer">
							<li id="simulate"><a href="simulate.php">Simulated Performance Monitoring: ECMWF60</a></li>
							<li id="simulate2"><a href="simulate2.php">Simulated Performance Monitoring: ECMWF 2009-02-15</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="geomonitoring"><a href="geomonitoring.php">Geophysical Performance</a>
						<ul class="detailContainer">
							<li id="geonwp"><a href="geonwp.php">Comparison to NWP</a></li>
							<li id="geomspps"><a href="geomspps.php">Comparison to MSPPS</a></li>
							<li id="geoamsre"><a href="geoamsre.php">Comparison to AMSR-E Snow & Sea Ice: Maps</a></li>
							<li id="geoamsretimeseries"><a href="geoamsretimeseries.php">Comparison to AMSR-E Snow & Sea Ice: Time Series</a></li>
							<li id="geoamsrehisto"><a href="geoamsrehisto.php">Comparison to AMSR-E Snow & Sea Ice: Histograms</a></li>
							<li id="geosnodas"><a href="geosnodas.php">Comparison to SNODAS Snow</a></li>
							<li id="geossmis"><a href="geossmis.php">Comparison to SSMIS Sea Ice</a></li>
							<li id="geobias"><a href="geobias.php">Performance Time Series</a></li>
							<li id="qcgeo"><a href="qcgeo.php">Performance Tables</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="intercomparison"><a href="intercomparison.php">Inter-Comparisons</a>
						<ul class="detailContainer">
							<li id="inter"><a href="inter.php">Inter-Comparison</a></li>
							<li id="qcinter"><a href="qcinter.php">Performance Tables</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="validation"><a href="validation.php">Validation</a>
						<ul class="detailContainer">
							<li id="validationraob"><a href="validationraob.php">Comparison to Radiosonde</a></li>
							<li id="validationhirs"><a href="validationhirs.php">Comparison to HIRS</a></li>
							<li id="validationcloudsat"><a href="validationcloudsat.php">Comparison to CloudSat</a></li>
							<li id="validationstage4timeseriesv"><a href="validationstage4timeseriesv.php">Comparison to Stage IV</a></li>
							<li id="validationtrmm"><a href="validationtrmm.php">Comparison to TRMM</a></li>
							<li id="validationtrmm2a12"><a href="validationtrmm2a12.php">Comparison to TRMM_2A12</a></li>
							<li id="validationipwg"><a href="validationipwg.php">IPWG Project</a></li>
							<li id="validationraingauge"><a href="validationraingauge.php">Comparison to Rain Gauge</a></li>
							<li id="validationrainradar"><a href="validationrainradar.php">Comparison to Rain Radar</a></li>
							<li id="validationcpctimeseriesv"><a href="validationcpctimeseriesv.php">Comparison to CPC</a></li>
							<li id="downloadvalidation"><a href="downloadvalidation.php">Performance Summaries</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="publications"><a href="publications.php">Publications</a>
					</li>
				</ul>
				<ul>
					<li id="download"><a href="download.php">Download</a>
						<ul class="detailContainer">
							<li id="downloaddap"><a href="downloaddap.php">DAP</a></li>
							<li id="downloaddata"><a href="downloaddata.php">EDRs &amp; DEPs</a></li>
							<li id="downloaddoc"><a href="downloaddoc.php">Documents</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="intranet"><a href="intranet.php">Intranet</a>
						<ul class="detailContainer">
							<li id="meeting"><a href="meeting.php">MIRS Meetings</a></li>
						</ul>
					</li>
				</ul>
				
				<!--ul>
					<li id="careers"><a href="careers.php">Positions Available</a>
					</li>
				</ul-->
			</div>
<!-- end of navlist -->
<?php 
// include the searchBox;
include('searchBox.inc'); 
// insert disclaimer language
include('includes/ProductDisclaimer.inc'); ?>
