			<div class="leftNav">
				<ul>
					<li id="index"><a href="index.php">Home</a></li>
				</ul>
				<ul>
					<li id="instruments"><a href="instruments.php">Instrument Descriptions</a></li>
				</ul>
				<ul>
					<li id="algorithm"><a href="algorithm.php">Algorithm</a></li>
				</ul>
				<ul>
					<li id="testbed"><a href="testbed.php">Testbed</a></li>
				</ul>
				<ul>
					<li id="products"><a href="products.php">Product Monitoring</a>
						<ul class="detailContainer">
							<li id="product"><a href="product.php">Daily Products - Low Res.</a></li>
							<li id="highresolution"><a href="highresolution.php">Daily Products - High Res.</a></li>
							<li id="vertical"><a href="vertical.php">Vertical Cross Section</a></li>
							<li id="dataqualityv"><a href="dataqualityv.php">Data Quality</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="climates"><a href="climates.php">Climate Monitoring</a></li>
				</ul>
				<ul>
					<li id="sensorsquality"><a href="sensorsquality.php">Sensor Quality</a></li>
				</ul>
				<ul>
					<li id="radiomonitoring"><a href="radiomonitoring.php">Radiometric Performance</a></li>
				</ul>
				<ul>
					<li id="simulatedmonitoring"><a href="simulatedmonitoring.php">Simulated Performance</a></li>
				</ul>
				<ul>
					<li id="geomonitoring"><a href="geomonitoring.php">Geophysical Performance</a></li>
				</ul>
				<ul>
					<li id="intercomparison"><a href="intercomparison.php">Inter-Comparisons</a></li>
				</ul>
				<ul>
					<li id="validation"><a href="validation.php">Validation</a></li>
				</ul>
				<ul>
					<li id="publications"><a href="publications.php">Publications</a></li>
				</ul>
				<ul>
					<li id="download"><a href="download.php">Download</a></li>
				</ul>
				<ul>
					<li id="intranet"><a href="intranet.php">Intranet</a></li>
				</ul>
			</div>
<!-- end of navlist -->
<?php 
// include the searchBox;
include('searchBox.inc'); 
// insert disclaimer language
include('includes/ProductDisclaimer.inc'); ?>
