			<div class="leftNav">
				<ul>
					<li id="index"><a href="index.php">Home</a>
					</li>
				</ul>
				<ul>
					<li id="instruments"><a href="instruments.php">Instrument Descriptions</a>
					</li>
				</ul>

				<ul>
					<li id="algorithm"><a href="algorithm.php">Algorithm</a>
					</li>
				</ul>
				<ul>
					<li id="testbed"><a href="testbed.php">Testbed</a>
					</li>
				</ul>
                                <ul>
                                        <li id="products"><a href="products.php">Product Monitoring</a>
                                        </li>
                                </ul>
                                <ul>
                                        <li id="climates"><a href="climates.php">Climate Monitoring</a>
					</li>
                                </ul>
				<ul>
					<li id="sensorsquality"><a href="sensorsquality.php">Sensor Quality</a>
					</li>
				</ul>
				<ul>
					<li id="radiomonitoring"><a href="radiomonitoring.php">Radiometric Performance</a>
						<ul class="detailContainer">
							<li id="radiogdas"><a href="radiogdas.php">TB Comparison (GDAS)</a></li>
							<li id="radiobiasgdas"><a href="radiobiasgdas.php">Calibration Bias Monitoring (GDAS)</a></li>
							<li id="radioecmwfv"><a href="radioecmwfv.php">TB Comparison (ECMWF)</a></li>
							<li id="radiobiasecmwf"><a href="radiobiasecmwf.php">Calibration Bias Monitoring (ECMWF)</a></li>
							<li id="radiogfs"><a href="radiogfs.php">TB Comparison (GFS)</a></li>
							<li id="qcradio"><a href="qcradio.php">Performance Tables</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="simulatedmonitoring"><a href="simulatedmonitoring.php">Simulated Performance</a>
					</li>
				</ul>
				<ul>
					<li id="geomonitoring"><a href="geomonitoring.php">Geophysical Performance</a>
					</li>
				</ul>
				<ul>
					<li id="intercomparison"><a href="intercomparison.php">Inter-Comparisons</a>
					</li>
				</ul>
				<ul>
					<li id="validation"><a href="validation.php">Validation</a>
					</li>
				</ul>
				<ul>
					<li id="publications"><a href="publications.php">Publications</a>
					</li>
				</ul>
				<ul>
					<li id="download"><a href="download.php">Download</a>
					</li>
				</ul>
				<ul>
					<li id="intranet"><a href="intranet.php">Intranet</a>
					</li>
				</ul>
			</div>
<!-- end of navlist -->
<?php 
// include the searchBox;
include('searchBox.inc'); 
// insert disclaimer language
include('includes/ProductDisclaimer.inc'); ?>
