			<div class="leftNav">

				<ul>
					<li id="index"><a href="index.php">Home</a></li>
				</ul>
				<ul>
					<li id="instruments"><a href="instruments.php">Instrument Descriptions</a></li>
				</ul>
				<ul>
					<li id="algorithm"><a href="algorithm.php">Algorithm</a></li>
				</ul>
				<ul>
					<li id="testbed"><a href="testbed.php">Testbed</a></li>
				</ul>
				<ul>
					<li id="products"><a href="products.php">Product Monitoring</a></li>
				</ul>
				<ul>
					<li id="climates"><a href="climates.php">Climate Monitoring</a></li>
				</ul>
				<ul>
					<li id="sensorsquality"><a href="sensorsquality.php">Sensor Quality</a></li>
				</ul>
				<ul>
					<li id="radiomonitoring"><a href="radiomonitoring.php">Radiometric Performance</a></li>
				</ul>
				<ul>
					<li id="simulatedmonitoring"><a href="simulatedmonitoring.php">Simulated Performance</a></li>
				</ul>
				<ul>
					<li id="geomonitoring"><a href="geomonitoring.php">Geophysical Performance</a>
						<ul class="detailContainer">
							<li id="geonwp"><a href="geonwp.php">Comparison to NWP</a></li>
							<li id="geomspps"><a href="geomspps.php">Comparison to MSPPS</a></li>
							<li id="geoamsrev"><a href="geoamsrev.php">Comparison to AMSR-E Snow & Sea Ice: Maps</a></li>
							<li id="geoamsretimeseries"><a href="geoamsretimeseries.php">Comparison to AMSR-E Snow & Sea Ice: Time Series</a></li>
							<li id="geoamsrehisto"><a href="geoamsrehisto.php">Comparison to AMSR-E Snow & Sea Ice: Histograms</a></li>
							<li id="geosnodas"><a href="geosnodas.php">Comparison to SNODAS Snow</a></li>
							<li id="geossmisv"><a href="geossmisv.php">Comparison to SSMIS Sea Ice</a></li>
							<li id="geobias"><a href="geobias.php">Performance Time Series</a></li>
							<li id="qcgeo"><a href="qcgeo.php">Performance Tables</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="intercomparison"><a href="intercomparison.php">Inter-Comparisons</a></li>
				</ul>
				<ul>
					<li id="validation"><a href="validation.php">Validation</a></li>
				</ul>
				<ul>
					<li id="publications"><a href="publications.php">Publications</a></li>
				</ul>
				<ul>
					<li id="download"><a href="download.php">Download</a></li>
				</ul>
				<ul>
					<li id="intranet"><a href="intranet.php">Intranet</a></li>
				</ul>

			</div>
<!-- end of navlist -->
<?php 
// include the searchBox;
include('searchBox.inc'); 
// insert disclaimer language
include('includes/ProductDisclaimer.inc'); ?>
