			<div class="leftNav">

				<ul>
					<li id="index"><a href="index.php">Home</a></li>
				</ul>
				<ul>
					<li id="instruments"><a href="instruments.php">Instrument Descriptions</a></li>
				</ul>

				<ul>
					<li id="algorithm"><a href="algorithm.php">Algorithm</a></li>
				</ul>
				<ul>
					<li id="testbed"><a href="testbed.php">Testbed</a></li>
				</ul>
                                <ul>
                                        <li id="products"><a href="products.php">Product Monitoring</a>
                                        </li>
                                </ul>
                                <ul>
                                        <li id="climates"><a href="climates.php">Climate Monitoring</a></li>
                                </ul>
				<ul>
					<li id="sensorsquality"><a href="sensorsquality.php">Sensor Quality</a>
						<ul class="detailContainer">
							<li id="nedtv"><a href="nedtv.php">NEDT Monitoring</a></li>
							<li id="fm"><a href="fm.php">Footprint Matching Quality</a></li>
						</ul>
					</li>
				</ul>
				<ul>
					<li id="radiomonitoring"><a href="radiomonitoring.php">Radiometric Performance</a></li>
				</ul>
				<ul>
					<li id="simulatedmonitoring"><a href="simulatedmonitoring.php">Simulated Performance</a></li>
				</ul>
				<ul>
					<li id="geomonitoring"><a href="geomonitoring.php">Geophysical Performance</a></li>
				</ul>
				<ul>
					<li id="intercomparison"><a href="intercomparison.php">Inter-Comparisons</a></li>
				</ul>
				<ul>
					<li id="validation"><a href="validation.php">Validation</a></li>
				</ul>
				<ul>
					<li id="publications"><a href="publications.php">Publications</a></li>
				</ul>
				<ul>
					<li id="download"><a href="download.php">Download</a></li>
				</ul>
				<ul>
					<li id="intranet"><a href="intranet.php">Intranet</a></li>
				</ul>
			</div>
<!-- end of navlist -->
<?php 
// include the searchBox;
include('searchBox.inc'); 
// insert disclaimer language
include('includes/ProductDisclaimer.inc'); ?>
