			<div class="searchBox">
			<form method="get" action="http://search.usa.gov/search"
				title="Search the STAR website">
				<label for="query-field" id="searchlbl">Search NOAA:</label>
		  	<input
		  	title="Search STAR"
		  	class="populate"
		  	type="text" name="query" id="query-field">&nbsp;<input 
		  	type="submit" value="Go" title="execute search" id="Go">
				<input type="hidden" name="affiliate" value="orbit.nesdis.noaa.gov_star"></form>
			</div>