<link rel="shortcut icon" href="images/favicon.ico">
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/print.css" media="print">


<script type="text/javascript" src="http://www.star.nesdis.noaa.gov/star/global/js/federated-analytics.js">
</script>
