#!/bin/ksh

# Set shell variables for use by ml3b.sh and gfs_land_climo.sh

#----------------------------------------------------------
# REQUIRED VARIABLES
#
# jcap     - spectral triangular truncation
# im       - number of Gaussian longitudes
# jm       - number of Gaussian latitudes
# mt       - mountain data resolution
# f1/2     - orography filter coefficients
# CHECKDIR - will look for the mask and terrain files for
#            the specified grid in this directory.  if they
#            do not exist, ml3b.sh is run to create them.            
# SAVEDIR  - program outputs are saved in this directory.
# WRKDIR   - temporary working directory.
# MASK_GFS_FILENAME - name of the landmask file for the
#                     target grid.  if it does not 
#                     exist in CHECKDIR, then ml3b.sh
#                     creates it with this name.
# OROG_GFS_FILENAME - name of the orography file for the
#                     target grid.  if it does not 
#                     exist in CHECKDIR, then ml3b.sh
#                     creates it with this name.
#----------------------------------------------------------

export jcap=62
export im=192
export jm=94

export mt=8

export f1=` expr $jcap + 1 `
export f2=` expr $jcap + 2 `

export SAVEDIR=/ptmp/wx20gg/save/t${jcap}

export CHECKDIR=/nwprod/fix

export WRKDIR=/ptmp/wx20gg/work

export OROG_GFS_FILENAME="global_orography.t${jcap}.grb"
export MASK_GFS_FILENAME="global_slmask.t${jcap}.grb"

#----------------------------------------------------------
# OPTIONAL VARIABLES to override the defaults in either
# script.  see scripts for definitions.
#----------------------------------------------------------

# jordan's source code that creates the mask/terrain
export TERRAINSORC=/global/save/wx23ja/terr06/ml01rg2.f

# create lots of output
export VERBOSE="YES"

# my program that creates the albedo based on the mask from jordan's program.
export GRIDGEN_SFC_EXE="/global/save/wx20gg/albedo_bosu/2jif/gridgen/src/gridgen_sfc.exe"

# the 0.05 degree max snow albedo data (path and name)
export MXSALB_SRC_FILE="/global/save/wx20gg/climo_fields/mxsnoalb_ariz/data/global_mxsnoalb.0.05.grb"

# the 0.05 degree snow-free albedo data (path and name)
export SFALB_SRC_FILE="/global/save/wx20gg/climo_fields/alb_bosu/data.grb/global_snowfree_albedo.0.05.grb"


