################################################################################
# This makefile was produced by fmjif at 17:21:11 on 97/02/24.
SHELL=	/bin/sh
CMD=	grb2index
FOPTS= -O3 -qarch=auto	
LOPTS=	
INCS=	
OBJS=	grb2index.o
LIBS=	-L/nwprod/lib -lg2_4 -lw3_4 -lbacio_4
################################################################################
$(CMD):	$(OBJS)
	ncepxlf $(LOPTS) $(OBJS) $(LIBS) -o $(CMD)
$(OBJS):	makefile $(INCS)
grb2index.o:	grb2index.f
	ncepxlf -c $(FOPTS) $*.f
clean:	
	-rm -f $(OBJS)
