       LOGICAL FUNCTION W3AI24(STRING1, STRING2,LENGTH)
C$$$   SUBPROGRAM  DOCUMENTATION  BLOCK
C
C FUNCT  W3AI24              TEST FOR MATCH OF TWO STRINGS
C   PRGMMR: LUKELIN          ORG: NMC421      DATE:94-08-31
C
C ABSTACT: TEST TWO STRINGS.
C     IF ALL EQUAL; OTHERWISE .FALSE.
C
C PROGRAM HISTORY LOG:
C   94-08-31  LUKE LIN
C
C USAGE:  II = W3AI24(STRING1,STRING2,LENGTH)
C
C   INPUT VARIABLES:
C     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
C     ------ --------- -----------------------------------------------
C     STRING1 ARG LIST  CHARACTER ARRAY TO MATCH WITH STRING2
C     STRING2 ARG LIST  CHARACTER ARRAY TO MATCH WITH STRING1
C
C   OUTPUT VARIABLES:
C     NAMES  INTERFACE DESCRIPTION OF VARIABLES AND TYPES
C     ------ --------- -----------------------------------------------
C     W3AI24 FUNCTION  LOGICAL .TRUE. IF S1 AND S2 MATCH ON ALL CHAR.,
C                      LOGICAL .FALSE. IF NOT MATCH ON ANY CHAR.
C
C ATTRIBUTES:
C   LANGUAGE: IBM VS FORTRAN
C   MACHINE:  NAS
C
C$$$
C
       CHARACTER*1 STRING1(*)
       CHARACTER*1 STRING2(*)
       INTEGER*4   LENGTH
C
          W3AI24 = .TRUE.
C
          DO 10 I = 1,LENGTH
             IF (STRING1(I).NE.STRING2(I))  GO TO 40
   10     CONTINUE
C
          RETURN
C
   40     CONTINUE
            W3AI24 = .FALSE.
            RETURN
C
          END
