      SUBROUTINE XDOPEN
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    XDOPEN      DUMMY SUBROUTINE
C   PRGMMR: KEYSER           ORG: W/NMC22    DATE: 07-02-92
C
C ABSTRACT: THIS SUBROUTINE AND THE CORRESPONDING ENTRIES: "ERRSET",
C   "XDCHEK", "XDCLOS", "XDWRIT", "XDREAD", AND "XDFORM"  ARE PLACED
C   HERE TO ALLOW CALLING ROUTINES WHICH RESIDE ON BOTH THE NAS AND
C   THE CRAY TO COMPILE.  THESE SUBROUTINES PERFORM NAS-SPECIFIC
C   FUNCTIONS, BUT HAVE NO CORRESPONDING FUNCTION ON THE CRAY. THERE-
C   FORE THIS SUBROUTINE IS A "DUMMY".  FT06 PRINT IS PROVIDED TO
C   ALERT THE USER THAT THE CALL TO THE SUBROUTINE RESULTS IN AN
C   IMMEDIATE RETURN WITH NO FUNCTION.
C
C PROGRAM HISTORY LOG:
C   92-07-02  D. A. KEYSER (W/NMC22)
C
C USAGE:    CALL XDOPEN
C
C REMARKS: NONE.
C
C ATTRIBUTES:
C   LANGUAGE: CRAY CFT77 FORTRAN
C   MACHINE:  CRAY Y-MP8/832
C
C$$$
C
      CHARACTER*6  ROUTIN(7)
C
      DATA  ROUTIN/'XDOPEN','ERRSET','XDCHEK','XDCLOS','XDWRIT',
     $             'XDREAD','XDFORM'/
C
      ICALL = 1
      GO TO 99
           ENTRY      ERRSET
      ICALL = 2
      GO TO 99
           ENTRY      XDCHEK
      ICALL = 3
      GO TO 99
           ENTRY      XDCLOS
      ICALL = 4
      GO TO 99
           ENTRY      XDWRIT
      ICALL = 5
      GO TO 99
           ENTRY      XDREAD
      ICALL = 6
      GO TO 99
           ENTRY      XDFORM
      ICALL = 7
   99 CONTINUE
      PRINT 1, ROUTIN(ICALL)
    1 FORMAT(/2X,'%%%% SUBR. ',A6,' HAS NO FCN ON THE CRAY, BUT IS ',
     $ 'PROVIDED TO ALLOW CODES TO COMPILE ON THE NAS & CRAY; RETURN ',
     $ 'TO CALLING PGM'//)
      RETURN
      END
