#!/bin/sh
#############################################################
# Set up environment for NAMRR Radiance Monitor job
#############################################################
set -xa
echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

export RUN_ENVIR=${RUN_ENVIR:-nco}
export envir=${envir:-prod}
export REGIONAL_RR=${REGIONAL_RR:-1}

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-nam}
export RUN=${RUN:-namrr}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}

export DATAROOT=${DATAROOT:-/tmpnwprod2}
export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p $DATA
cd $DATA

###############################################################
# This block can be modified for different test environment
###############################################################
if [ $RUN_ENVIR = nco -a $envir != prod ]; then
  export SENDDBN=${SENDDBN:-NO}
fi


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z
export rgnHH=${rgnHH:-$cycle}
export rgnTM=${rgnTM:-tm06}

##############################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# VERBOSE  - Specify Verbose Output in exglobal
##############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export VERBOSE=${VERBOSE:-YES}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-${UTILROOT}/ush}
export utilexec=${utilexec:-${UTILROOT}/exec}


##############################################
# Specify Execution Areas
##############################################
export HOMEnamrr=${HOMEnamrr:-${NWROOT}/namrr_radmon.v2.0.0}  # need to use version here
export SCRnamrr=${SCRnamrr:-$HOMEnamrr/scripts}

export HOMEgdas=${HOMEgdas:-${NWROOT}/gdas.$gdas_ver}
export PARMgdas=${PARMgdas:-$HOMEgdas/parm}
export SCRgdas=${SCRgdas:-$HOMEgdas/scripts}
export FIXgdas=${FIXgdas:-$HOMEgdas/fix}

export HOMEradmon=${HOMEradmon:-/${NWROOT}/radmon_shared.${radmon_shared_ver}}
export EXECradmon=${EXECradmon:-$HOMEradmon/exec}
export FIXradmon=${FIXradmon:-${FIXgdasradmon}}
export USHradmon=${USHradmon:-$HOMEradmon/ush}


###################################
# source the parm file
###################################
.  ${PARMgdas}/gdas_radmon.parm


#############################################
# Run setpdy and initialize PDY variables
#############################################
${utilscript}/setpdy.sh
source ./PDY


#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
export TANKverf=${TANKverf:-/com/verf/${envir}}
export TANKverf_rad=${TANKverf_rad:-${TANKverf}/radmon.${PDY}}
export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COMIN=${COMIN:-$COM_IN/${RUN}.${PDY}}

mkdir -p -m 775 $TANKverf_rad
 
env

########################################
# Set necessary environment variables
########################################
export RAD_AREA=${RAD_AREA:-glb}

export biascr=${biascr:-$COMIN/gdas1.t${cyc}z.abias}
export radstat=${radstat:-$COMIN/gdas1.t${cyc}z.radstat}

msg="JOB HAS STARTED"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
echo "EXECUTING ${SCRnamrr}/exnamrr_vrfyrad.sh.ecf"
${RADMONSH:-${SCRnamrr}/exnamrr_vrfyrad.sh.ecf} ${PDY} ${cyc}
########################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

################################
# Remove the Working Directory
################################
KEEPDATA=${KEEPDATA:-NO}
cd $DATAROOT
if [ ${KEEPDATA} = NO ] ; then 
  rm -rf $DATA 
fi

date

