#!/bin/sh
#
FC=     ifort 
ARCH     = 
FOPTS=   -O2 -g -traceback -convert big_endian
CMD=    ../ecm_gfs_look_alike
LIBDIR= ../../nwprod/lib
                                                                                                
SRCS=  ecm_gfs_look_alike.f90
LIBS=	${LIBDIR}/libbacio_4.a \
	${LIBDIR}/libw3lib-2.0_4.a \
	${LIBDIR}/libbufr_4_E8.a 
$(CMD): $(SRCS)
	$(FC) $(FOPTS) $(SRCS) $(LIBS) -o $(CMD)

