      SUBROUTINE INSCRIBE (A,B,C,R)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    INSCRIBE    ESTIMATES THE CURVATURE OF A CONTOUR
C   PRGMMR: KRISHNA KUMAR       ORG: W/NP12    DATE: 1999-07-01
C
C ABSTRACT: DESCRIBES THE ARC THAT INSCRIBES THREE POINTS IN A CURVE.
C
C PROGRAM HISTORY LOG:
C   94-12-13  ORIGINAL AUTHOR RALPH JONES.
C   94-12-15  HENRICHSEN    ADD DOCBLOCK.
C   94-12-22  LUKE LIN      CONVERT IT TO CFT-77.
C 1999-07-01  KRISHNA KUMAR CONVERTED FROM CRAY TO IBM RS/6000
C
C USAGE:    CALL INSCRIBE (A,B,C,R)
C   INPUT ARGUMENT LIST:
C     A        - REAL*4 1ST LOACTION ON A CURVE.
C     B        - REAL*4 2ND LOACTION ON A CURVE.
C     C        - REAL*4 3RD LOACTION ON A CURVE.
C     INARG2   - TYPE.  EXPLAIN FUNCTION IF CONTROL VARIABLE.
C
C   OUTPUT ARGUMENT LIST:
C     R        - REAL*4 THE RADIUS OF THE ARC DESCRIBED BY A,B,C.
C
C
C   OUTPUT FILES:
C     FT06F001 - INCLUDE IF ANY PRINTOUT
C
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
C
      REAL A,B,C,R
      REAL S
C
      S = 0.5*(A+B+C)
      RAD = S*(S-A)*(S-B)*(S-C)
C
      IF(RAD.LT.1.0E-6) THEN
        R = 10000.0
C
C       WRITE(6,FMT='('' INSCRIBE: '',
C    1     '' <<< RADICAND OUT OF RANGE ('',E12.3,'' ) '',
C    2        ''  -  RADIUS SET TO '',F7.1,''  >>>'',/)')RAD,R
C
      ELSE
C
       DENOM = 4.0*SQRT(RAD)
C
        R = A*B*C/DENOM
C
      END IF
      RETURN
      END
