#!/bin/sh

###################################################################
#  Note:  MinMon/parm/MinMon.ver file must be sourced before this file
###################################################################
export MY_MACHINE=${MY_MACHINE:-wcoss}

export MY_MINMON=/gpfs/gd2/emc/da/noscrub/Edward.Safford/Gmon_461/util/Minimization_Monitor

export HOMEgdasgmon=${MY_MINMON}/nwprod/gdas_minmon.v${gdas_minmon_ver}
export HOMEgmon=${MY_MINMON}/nwprod/minmon_shared.v${minmon_shared_ver}

export MINMON_DE=${MINMON_DE:-${MY_MINMON}/data_xtrct}
export DE_SCRIPTS=${DE_SCRIPTS:-${MINMON_DE}/ush}

export MINMON_IG=${MINMON_IG:-${MY_MINMON}/image_gen}
export IG_SCRIPTS=${IG_SCRIPTS:-${MINMON_IG}/ush}
export IG_GRDS=${IG_GRDS:-${MINMON_IG}/grds}
export IG_PARM=${IG_PARM:-${MINMON_IG}/parm}

export envir=prod
export DATA_IN=${DATA_IN:-/stmpp1/${LOGNAME}/minmon}	# working directory

export LOGdir=${LOGdir:-/ptmpp1/${LOGNAME}/logs}
export jlogfile=${jlogfile:-${LOGdir}/minmon.DE.}
export TANKverf=${TANKverf:-/u/Edward.Safford/nbns}	# storage directory

export WEBUSER=${WEBUSER:-esafford} 		# user name on webserver
export WEBSERVER=${WEBSERVER:-emcrzdm.ncep.noaa.gov}
export WEBDIR=${WEBDIR:-/home/people/emc/www/htdocs/gmb/gdas/radiance/esafford/gsi_stat/pngs}					# directory on webserver

export AREA=${AREA:-glb}			# glb | rgn, default to global

#
#  Utilities used by the GMon package
#
export NCP=${NCP:-"/bin/cp -f"}
export Z=${Z:-"gz"}

if [[ $MY_MACHINE = "wcoss" ]]; then
   shell=sh
   . /usrx/local/Modules/default/init/${shell}
   module load lsf

   export SUB="bsub"
   export NWPROD=/nwprod
   export COMPRESS=/usrx/local/bin/pigz
   export UNCOMPRESS="/usrx/local/bin/unpigz -f"
   export RSYNC=/usr/bin/rsync
else    # zeus 
   shell=sh
   /usr/bin/modulecmd $shell load ncep

   export SUB=/apps/torque/default/bin/qsub
   export NWPROD=/scratch1/portfolios/NCEPDEV/da/save/Michael.Lueken/nwprod
   export COMPRESS=gzip
   export UNCOMPRESS="gunzip -f"
fi

export NDATE=${NWPROD}/util/exec/ndate
