#!/bin/sh

if [[ $MINMON_CONFIG -ne 1 ]]; then

   export MINMON_CONFIG=1

   export MY_MACHINE=wcoss2

   export MY_MINMON=${MY_MINMON:-/lfs/h2/emc/da/noscrub/Edward.Safford/git/gsi/GSI/util/Minimization_Monitor}


   export HOMEgdas=${MY_MINMON}/nwprod/gdas
   export HOMEgfs=${MY_MINMON}/nwprod/gfs

   export M_FIXgdas=${M_FIXgdas:-${HOMEgdas}/fix}
   export M_FIXgfs=${M_FIXgfs:-${HOMEgfs}/fix}

   export HOMEnam=${MY_MINMON}/nwprod/nam_minmon
   export HOMEminmon=${MY_MINMON}/nwprod/minmon_shared

   export MINMON_DE=${MINMON_DE:-${MY_MINMON}/data_xtrct}
   export M_DE_SCRIPTS=${M_DE_SCRIPTS:-${MINMON_DE}/ush}

   export MINMON_IG=${MINMON_IG:-${MY_MINMON}/image_gen}
   export M_IG_SCRIPTS=${M_IG_SCRIPTS:-${MINMON_IG}/ush}
   export M_IG_GRDS=${M_IG_GRDS:-${MINMON_IG}/grds}
   export M_IG_PARM=${M_IG_PARM:-${MINMON_IG}/parm}

   export MY_STMP=${MY_STMP:-/lfs/h2/emc/stmp/Edward.Safford}
   export MY_PTMP=${MY_PTMP:-/lfs/h2/emc/ptmp/Edward.Safford}

   export envir=${RUN_ENVIR:-prod}

   #
   # working directory
   #
   export DATA_IN=${DATA_IN:-${MY_STMP}/${MINMON_SUFFIX}/${RUN}/minmon}	 #rename to WORK_DIR
   export LOGdir=${LOGdir:-${MY_PTMP}/logs/${MINMON_SUFFIX}/${RUN}/minmon}

   export MY_TANKDIR=${MY_TANKDIR:-/lfs/h2/emc/da/noscrub/Edward.Safford/nbns}
   export M_TANKverf=${M_TANKverf:-${MY_TANKDIR}}	
   export MIN_IMGN_TANKDIR=${MY_TANKDIR}/imgn/${MINMON_SUFFIX}

   export WEBUSER=${WEBUSER:-esafford}
   export WEBSERVER=${WEBSERVER:-emcrzdm}
   export WEBDIR=${WEBDIR:-/home/people/emc/www/htdocs/gmb/gdas/radiance/esafford/gsi_stat/pngs}

   #
   #  Utilities used by the MinMon package
   #
   export NCP=${NCP:-"/bin/cp -f"}
   export Z=${Z:-"gz"}

   if [[ $MY_MACHINE = "wcoss_d" ]]; then
      shell=sh
      source /usrx/local/prod/lmod/lmod/init/${shell}

      export MODULEPATH=/usrx/local/prod/lmod/lmod/modulefile/sCore:/usrx/local/prod/modulefiles/core_third:/usrx/local/prod/modulefiles/defs:/gpfs/dell1/nco/ops/nwprod/modulefiles/core_prod:/usrx/local/dev/modulefiles
      module purge

      module load ips/18.0.1.163
      module load metplus/2.1
      module load lsf/10.1
      module load prod_util/1.1.6
      module load pm5/1.0
      module load GrADS/2.2.0

      export SUB=`which bsub`
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"
      export RSYNC=/usr/bin/rsync

   elif [[ $MY_MACHINE = "wcoss2" ]]; then 
      module load prod_util/2.0.10
      module load util_shared/1.4.0
      module load perl/5.32.0

      #
      #  Note this GrADS mod is a temporary solution.  NCO is to 
      #  provide a more permanent fix on wcoss2 at some point.
      #
      module use /apps/test/modules
      module load GrADS/2.2.1-cce-11.0.4

      export SUB=`which qsub`
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"
      export RSYNC=`which rsync`

   elif [[ $MY_MACHINE = "cray" ]]; then
      sys=`hostname`
      sys1=`echo $sys | cut -c1`
      echo $sys1

      # 
      #  module pm5 needs to have SITE set in order to load
      #  Why?  Not at all clear, but it sure does fail w/o SITE set. 
      #
      if [[ $sys1 == "s" ]]; then
         export SITE=SURGE
      else 
         export SITE=LUNA
      fi

      . /opt/modules/3.2.6.7/init/sh

      module use /opt/modulefiles
      module load xt-lsfhpc

      module use /gpfs/hps/nco/ops/nwprod/modulefiles
      module load prod_util        # defines $NDATE among other things
      module load prod_envir

      module use /usrx/local/prod/modulefiles
      module load pm5

      export SUB="bsub"
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"
      export RSYNC=/usr/bin/rsync

   elif [[ $MY_MACHINE = "hera" ]]; then
      shell=sh
      . $MODULESHOME/init/$shell
      module load grads/2.0.2

      export GRADS=`which grads`
      export STNMAP=`which stnmap`

      export SUB=/apps/slurm/default/bin/sbatch
      export NWPROD=/home/Edward.Safford/bin
      export NDATE=${NWPROD}/ndate
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"

   elif [[ $MY_MACHINE = "s4" ]]; then
      shell=sh
      . $MODULESHOME/init/$shell
      module load grads/2.2.1
      module load license_intel/S4
      module use /data/prod/hpc-stack/modulefiles/stack
      module load hpc/1.1.0 hpc-intel/18.0.4 prod_util/1.2.2

      export GRADS=`which grads`
      export STNMAP=`which stnmap`

      export SUB=/usr/bin/sbatch
      export NWPROD=/data/prod/hpc-stack/intel-18.0.4/prod_util/1.2.2/bin
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"

   elif [[ $MY_MACHINE = "jet" ]]; then
      shell=sh
      . $MODULESHOME/init/$shell
      module load grads/2.2.1
      module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
      module load hpc/1.1.0 hpc-intel/18.0.5.274 prod_util/1.2.2

      export GRADS=`which grads`
      export STNMAP=`which stnmap`

      export SUB=/apps/slurm/default/bin/sbatch
      export NWPROD=/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/prod_util/1.2.2/bin
      export COMPRESS=gzip
      export UNCOMPRESS="gunzip -f"
   fi

   export NDATE=${NDATE:-${NWPROD}/util/exec/ndate}

else
   echo "MinMon_config already loaded"
fi
