#!/bin/sh
#------------------------------------------------------------------------------
#
#  MinMon_user_settings
#
#  Modify this file in order to change behavior of the GMon package 
#------------------------------------------------------------------------------

if [[ $MINMON_USER_SETTINGS -ne 1 ]]; then
   
   export MINMON_USER_SETTINGS=1

   #
   #  ACCOUNT is used on zeus only for use with the qsub -a flag.  It is
   #  empty on other platforms.
   #
   export ACCOUNT=${ACCOUNT:-fv3-cpu}

   #
   #  PROJECT is used on wcoss only with the bjob -P flag.  It is 
   #  empty on other platforms.
   #
   export PROJECT=${PROJECT:-}

   #
   #  JOB_QUEUE is used on wcoss only with the bjob -q flag.  It is 
   #  empty on other platforms.
   #
   export JOB_QUEUE=${JOB_QUEUE:-dev_shared}

   #
   #  RUN_ONLY_ON_DEV  1 = dev machine only, 0 = run anywhere
   #
   export RUN_ONLY_ON_DEV=${RUN_ONLY_ON_DEV:-1}

   #
   #  WORKDIR is working directory (tmp space)
   #
   if [[ ${#RUN} -le 0 ]]; then
      export WORKDIR=${MY_STMP}/${LOGNAME}/${MINMON_SUFFIX}/minmon
   else
      export WORKDIR=${MY_STMP}/${LOGNAME}/${MINMON_SUFFIX}/${RUN}/minmon
   fi

   # 
   #  GLB_AREA indicates the valid area of the data source
   #   1 = area is global
   #   0 = area is regional (not global)
   #
   export GLB_AREA=${GLB_AREA:-1}                       

   #
   #  DO_ERROR_RPT 1 = mail any error reports to the MAIL_TO and MAIL_CC lists
   #               0 = take no action on any error reports (they will be in the
   #                   ${TANKverf}/${suffix}/minmon_[yyyymmdd]/ directory)
   export DO_ERROR_RPT=${DO_ERROR_RPT:-0}

   #
   #  DO_ARCHIVE   1 = copy data to hpss and to prod machine at completion of each day
   #               0 = no data archiving (data will remain in TANKDIR on this machine)
   #
   export DO_ARCHIVE=${DO_ARCHIVE:-0}

   #
   #  MAIL_TO is the mail recpient list for error reporting
   #
   export MAIL_TO=${MAIL_TO:-""}

   #
   #  MAIL_CC is the mail recpient cc list for error reporting
   #
   export MAIL_CC=${MAIL_CC:-""}

   #
   #  KEEPDATA is the control flag for preserving/deleting the working
   #  directory.  YES = keep the WORKDIR directory and contents
   #              NO  = delete the WORKDIR directory and contents
   #
   export KEEPDATA=YES

   #
   #  If TANK_USE_RUN =1 then the TANKdir will resolve to :
   #      ${MY_TANKDIR}/${MINMON_SUFFIX}/$RUN.$PDY/minmon/[data_files]
   #  instead of:
   #      ${MY_TANKDIR}/${MINMON_SUFFIX}/minmon.$RUN.$PDY/[data_files]
   #
   export TANK_USE_RUN=1

else
  echo "MinMon_user_config already loaded"
fi

