#!/usr/bin/env python
# getgfsnctime
# cory.r.martin@noaa.gov
# 2019-10-17
# script to return initial and valid time 
# for specified netCDF file
import sys
import gsi_utils
import datetime

if __name__ == '__main__':
  if len(sys.argv) < 2:
    print('usage: getgfsnctime ncfile.nc <init|valid|fhour>')
    sys.exit(1)
  NCFile = sys.argv[1]
  if len(sys.argv) == 3:
    option = sys.argv[2]
  else:
    option = None
  inittime, validtime, nfhour = gsi_utils.get_timeinfo(NCFile)
  if option == 'init':
     print(inittime.strftime("%Y%m%d%H%M"))
  elif option == 'valid':
     print(validtime.strftime("%Y%m%d%H%M"))
  elif option == 'fhour':
     print(nfhour)
  else:
     print(sys.argv[1])
     print('Initial time: '+inittime.strftime("%Y-%m-%d %H:%M"))
     print('Valid time: '+validtime.strftime("%Y-%m-%d %H:%M"))
     print('Forecast hour: '+str(nfhour))
  sys.exit(0)
