#!/usr/bin/env python
# getncdimlen
# cory.r.martin@noaa.gov
# 2019-10-17
# script to return length of requested dimension
# for specified netCDF file
import sys
import gsi_utils

if __name__ == '__main__':
  if len(sys.argv) != 3:
    print('usage: getncdimlen ncfile.nc dimname')
    sys.exit(1)
  NCFile = sys.argv[1]
  NCDim = sys.argv[2]
  FileDims = gsi_utils.get_ncdims(NCFile)
  print(FileDims[NCDim])
  sys.exit(0)
