#!/bin/sh
#############################################################
# Set up environment for NAM Radiance Monitor job
#############################################################
set -xa
echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

export RUN_ENVIR=${RUN_ENVIR:-nco}
export envir=${envir:-prod}
export REGIONAL_RR=${REGIONAL_RR:-1}

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-nam}
export RUN=${RUN:-nam}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}

export RADMON_SUFFIX=${RADMON_SUFFIX:-$RUN}
export DATAROOT=${DATAROOT:-/tmpnwprod2}
export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p $DATA
cd $DATA

###############################################################
# This block can be modified for different test environment
###############################################################
if [ $RUN_ENVIR = nco -a $envir != prod ]; then
  export SENDDBN=${SENDDBN:-NO}
fi


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z
export rgnHH=${rgnHH:-$cycle}
export rgnTM=${rgnTM:-tm06}

##############################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# VERBOSE  - Specify Verbose Output in exglobal
##############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export VERBOSE=${VERBOSE:-YES}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-${UTILROOT}/ush}
export utilexec=${utilexec:-${UTILROOT}/exec}


##############################################
# Specify Execution Areas
##############################################
export HOMEnam=${HOMEnam:-${NWROOT}/nam_radmon.v2.0.0}  # need to use version here
export SCRnam=${SCRnam:-$HOMEnam/scripts}
export PARMnam=${PARMnam:-${HOMEnam}/parm}


###################################
# source the parm file
###################################
.  ${PARMnam}/nam_radmon.parm

#export HOMEgdas=${HOMEgdas:-${NWROOT}/gdas.$gdas_ver}
#export PARMgdas=${PARMgdas:-$HOMEgdas/parm}
#export SCRgdas=${SCRgdas:-$HOMEgdas/scripts}
#export FIXgdas=${FIXgdas:-$HOMEgdas/fix}

#  Q:  can these go to parm file?
export HOMEradmon=${HOMEradmon:-/${NWROOT}/radmon_shared.${radmon_shared_ver}}
export EXECradmon=${EXECradmon:-$HOMEradmon/exec}
export FIXradmon=${FIXradmon:-${FIXgdasradmon}}
export USHradmon=${USHradmon:-$HOMEradmon/ush}


#############################################
# Run setpdy and initialize PDY variables
#############################################
if [[ $MY_MACHINE != "theia" ]]; then
   ${utilscript}/setpdy.sh
   source ./PDY
fi

#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
export TANKverf=${TANKverf:-/com/verf/${envir}}
export TANKverf_rad=${TANKverf_rad:-${TANKverf}/radmon.${PDY}}
export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COMIN=${COMIN:-$COM_IN/${RUN}.${PDY}}

mkdir -p -m 775 $TANKverf_rad
 
env

########################################
# Set necessary environment variables
########################################
export RAD_AREA=${RAD_AREA:-rgn}
export CYCLE_INTERVAL=${CYCLE_INTERVAL:-1}


#####################################################################
# Note:  The organization to the radstat catch-up files follows
#        this logic:
#####################################################################

case $cyc in
   00) export rgnHH=t00z
       export rgnTM=tm00;;
   01) export rgnHH=t06z
       export rgnTM=tm05;;
   02) export rgnHH=t06z
       export rgnTM=tm04;;
   03) export rgnHH=t06z
       export rgnTM=tm03;;
   04) export rgnHH=t06z
       export rgnTM=tm02;;
   05) export rgnHH=t06z
       export rgnTM=tm01;;
   06) export rgnHH=t06z
       export rgnTM=tm00;;
   07) export rgnHH=t12z
       export rgnTM=tm05;;
   08) export rgnHH=t12z
       export rgnTM=tm04;;
   09) export rgnHH=t12z
       export rgnTM=tm03;;
   10) export rgnHH=t12z
       export rgnTM=tm02;;
   11) export rgnHH=t12z
       export rgnTM=tm01;;
   12) export rgnHH=t12z
       export rgnTM=tm00;;
   13) export rgnHH=t18z
       export rgnTM=tm05;;
   14) export rgnHH=t18z
       export rgnTM=tm04;;
   15) export rgnHH=t18z
       export rgnTM=tm03;;
   16) export rgnHH=t18z
       export rgnTM=tm02;;
   17) export rgnHH=t18z
       export rgnTM=tm01;;
   18) export rgnHH=t18z       # dayfile changes here
       export rgnTM=tm00;;
   19) export rgnHH=t00z
       export rgnTM=tm05;;
   20) export rgnHH=t00z
       export rgnTM=tm04;;
   21) export rgnHH=t00z
       export rgnTM=tm03;;
   22) export rgnHH=t00z
       export rgnTM=tm02;;
   23) export rgnHH=t00z
       export rgnTM=tm01;;
esac

export biascr=${biascr:-$COMIN/${RADMON_SUFFIX}.${rgnHH}.satbiasc.${rgnTM}}
export radstat=${radstat:-$COMIN/${RADMON_SUFFIX}.${rgnHH}.radstat.${rgnTM}}


msg="JOB HAS STARTED"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
echo "EXECUTING ${SCRnam}/exnam_vrfyrad.sh.ecf"
${RADMONSH:-${SCRnam}/exnam_vrfyrad.sh.ecf} ${PDY} ${cyc}
########################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

################################
# Remove the Working Directory
################################
KEEPDATA=${KEEPDATA:-NO}
cd $DATAROOT
if [ ${KEEPDATA} = NO ] ; then 
  rm -rf $DATA 
fi

date

