      SUBROUTINE HILO(IDOTS,JDOTS,LHTYPE,NTRPR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:  HILO          HIGH/LOW CHARACTER ROTATOR
C   PRGMMR: KRISHNA KUMAR       ORG: NP12    DATE:1999-07-01
C
C ABSTRACT: DRAWS LARGE L OR H AT CENTER SPECIFIED BY IDOTS,JDOTS...
C           ...LHTYPE IS A 2 WORD PARAMETER...
C           ...LHTYPE(1)=THE ROTATION   FLAG=0,1,2 OR 3 FOR A   0,90,
C           180 OR 270 DEGREE COUNTER-CLOCKWISE ROTATION...
C          ...LHTYPE(2)= 1 FOR L,   =2 FOR  H
C          ...NTRPR  IS HOLLERITH TEXT TO BE PRINTED (A3) FORMAT BLO
C          CENTER.
C
C PROGRAM HISTORY LOG:
C   ??-??-??  AUTHOR UNKNOWN
C   93-04-07  LILLY         CONVERT SUBROUTINE TO FORTRAN 77
C   96-02-21  LIN           CONVERT TO CFT-77.
C 1999-07-01  KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM RS/6000.
C
C USAGE:    CALL HILO( IDOTS, JDOTS, LHTYPE, NTRPR )
C   INPUT ARGUMENT LIST:
C     INARG1   - GENERIC DESCRIPTION, INCLUDING CONTENT, UNITS,
C     INARG2   - TYPE.  EXPLAIN FUNCTION IF CONTROL VARIABLE.
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     WRKARG   - GENERIC DESCRIPTION, ETC., AS ABOVE.
C     OUTARG1  - EXPLAIN COMPLETELY IF ERROR RETURN
C     ERRFLAG  - EVEN IF MANY LINES ARE NEEDED
C
C   INPUT FILES:   (DELETE IF NO INPUT FILES IN SUBPROGRAM)
C     DDNAME1  - GENERIC NAME & CONTENT
C
C   OUTPUT FILES:  (DELETE IF NO OUTPUT FILES IN SUBPROGRAM)
C     DDNAME2  - GENERIC NAME & CONTENT AS ABOVE
C     FT06F001 - INCLUDE IF ANY PRINTOUT
C
C REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
      DIMENSION  IBOXT(2,4),JBOXT(2,4)
      DIMENSION  IDELLO(3,4),JDELLO(3,4)
      DIMENSION  IDELHI(4,4),JDELHI(4,4)
      DIMENSION  HGTHVV(3)
C
      CHARACTER*12 NTRPR
      CHARACTER*1 LDOLL,LLB,LBLK
      CHARACTER*1 LNULL
      CHARACTER*1 LTRPR(4)
      CHARACTER*1  LSAVE
      CHARACTER*4  IDARK
      CHARACTER*4  JKTRPR
      CHARACTER*2  ITEXT
      CHARACTER*2  LPER
C
      INTEGER    LHTYPE(2)
      INTEGER    IROTPR(2)
C
      EQUIVALENCE (JKTRPR,LTRPR)
C
      DATA LDOLL / '$' /
C///  DATA LDOLL /Z5B/
      DATA LBLK / ' ' /
C///  DATA LBLK / Z40 /
      DATA LLB / '#' /
C///  DATA LLB / Z7B /
      DATA     IBOXT /-19,+21, +33,-31, +19,-21, -33,+31/
C
      DATA     JBOXT /-33,+31, -19,+21, +33,-31, +19,-21/
C
C
      DATA IDELLO /-19,-19,-17, +09,-31,+19, -21,+13,-19, -15,-09,-33/
C
      DATA JDELLO /-15,-09,-33, -19,-19,-17, +09,-31,+19, -21,+13,-19/
C
C
      DATA IDELHI /-19,-19,+15,-17, -15,-31,-31,+13, -21,+13,-21,-19,
     4             +09,-09,-09,-27/
C
      DATA JDELHI /+09,-09,-09,-27, -19,-19,+15,-17, -15,-31,-31,+13,
     4             -21,+13,-21,-19/
C
C
      DATA     HGTHVV /16.0,17.0,17.0/
C     ...FOR CHAR SET SELECTION IN ORDER ...HORIZ, VERT, VERT...
      DATA  IDELC /-5/
      DATA  JDELC /-6/
C
C     ...WHICH ARE DISPLACEMENTS FOR CENTRAL X-MARK...
      DATA MAXJ  /7800/
      DATA MAXI  /4000/
      DATA IDARK /'AA$ '/
C///  DATA IDARK /ZC1C15B4B/
C///  DATA     LPER /2H.$/
      DATA     LPER /'.$'/
C///  DATA     LPER /Z4B5B/
C
      LNULL = CHAR(00)
C
      IP = IDOTS
      JP = JDOTS
C     ...OBTAIN INDEXER FOR ROTATION FLAG....
      NX = LHTYPE(1) + 1
C     ...CHECK FOR VALID RANGES OF NX IF NOT VALID DEFALT TO 1.
      IF ( NX .GT. 4 ) NX = 1
      IF ( NX .LE. 0 ) NX = 1
C     ...BOX TEST TO ENSURE ENTIRE FIGURE WILL GO ON PAGE...
      IF((IP + IBOXT(1,NX)) .LT. 1) GO TO 500
      IF((IP + IBOXT(2,NX)) .GT. MAXI) GO TO 500
      IF((JP + JBOXT(1,NX)) .LT. 1) GO TO 500
      IF((JP + JBOXT(2,NX)) .GT. MAXJ) GO TO 500
C///  JKTRPR = NTRPR
      JKTRPR = NTRPR(1:4)
      IF ( NX .LE. 2 ) GO TO 200
C     ...TEXT MUST BE REVERSED FOR 180 AND 270 DEGREE ROTATION...
      IF( LTRPR(1) .EQ. LDOLL .OR. LTRPR(1) .EQ. LNULL ) GO TO 200
      IF ( LTRPR(1) .EQ. LBLK ) GO TO 130
      IF ( LTRPR(1) .EQ. LLB ) GO TO 130
C.... POSSIBLE THREE CHARACTERS...
      IF ( LTRPR(2) .EQ. LDOLL .OR. LTRPR(2) .EQ. LNULL) GO TO 200
      IF ( LTRPR(3) .EQ. LDOLL .OR. LTRPR(3) .EQ. LNULL) GO TO 120
C     REVERSE N1 AND N3
      LSAVE = LTRPR(3)
      LTRPR(3) = LTRPR(1)
      LTRPR(1) = LSAVE
      GO TO 200
  120 CONTINUE
C     REVERSE N1 AND N2
      LSAVE = LTRPR(2)
      LTRPR(2) = LTRPR(1)
      LTRPR(1) = LSAVE
      GO TO 200
  130 CONTINUE
C.... POSSIBLE TWO CHARACTERS...
      IF ( LTRPR(2) .EQ. LBLK ) GO TO 200
      IF ( LTRPR(2) .EQ. LLB ) GO TO 200
C    REVERSE N2 AND N3
      LSAVE = LTRPR(3)
      LTRPR(3) = LTRPR(2)
      LTRPR(2) = LSAVE
      GO TO 200
C     ...PLOT ENCIRCLED X MARK AT CENTER PT
  200 CONTINUE
      ICENT = IP + IDELC
      JCENT = JP + JDELC
      HGT = 2.0
      ITEXT(1:2) = LPER(1:2)
      IROTPR(1) = 0
      IROTPR(2) = 2
      CALL  PUTLAB(ICENT,JCENT,HGT,ITEXT,0.0,1,IROTPR,0)
      IROTPR(1) = LHTYPE(1)
      LH = LHTYPE(2)
      IF(LH - 1) 300,322,300
  300 CONTINUE
      IF(LH - 2) 311,422,311
  311 CONTINUE
      PRINT  313, LHTYPE
  313 FORMAT(1H0,10X, 'INVALID LHTYPE GIVEN TO SUBR HILO', 5X,2Z4,/1H0)
      RETURN
  322 CONTINUE
C     ...COMES HERE IF LOW ...
      IPR = IP + IDELLO(3,NX)
      JPR = JP + JDELLO(3,NX)
      IROTPR(2) = 0
C     PRINT *, ' IN HILO : JKTRPR=', NTRPR, JKTRPR
      CALL  PUTLAB(IPR,JPR,HGT,JKTRPR,0.0,3,IROTPR,0)
      DO  355  I=1,2
C     ...HORIZ BAR , THEN VERT BAR...
      HGT = HGTHVV(I)
      ILL = IP + IDELLO(I,NX)
      JLL = JP + JDELLO(I,NX)
      IROTPR(2) = 0
      CALL  PUTLAB(ILL,JLL,HGT,IDARK,0.0,2,IROTPR,0)
  355 CONTINUE
      RETURN
  422 CONTINUE
C     ...COMES HERE IF HIGH...
      IPR = IP + IDELHI(4,NX)
      JPR = JP + JDELHI(4,NX)
      IROTPR(2) = 0
      CALL  PUTLAB(IPR,JPR,HGT,JKTRPR,0.0,3,IROTPR,0)
      DO 433  I = 1,3
      HGT = HGTHVV(I)
      ILL = IP + IDELHI(I,NX)
      JLL = JP + JDELHI(I,NX)
      IROTPR(2) = 0
      CALL  PUTLAB(ILL,JLL,HGT,IDARK,0.0,2,IROTPR,0)
  433 CONTINUE
      RETURN
  500 CONTINUE
      PRINT  511, IP,JP
  511 FORMAT(1H0,10X, 'CENTER PLOT FELL OUT-OF-BOUNDS AT I = ',I5,
     X      5X, 4HJ = , I5)
      RETURN
      END
