'open wbt126.ctl'
'set mpdset hires'
'set lat 20 60'
'set lon 230 300'
'set display color white'
'open ../../warmt382/7daymean/wbt382.ctl'
'colors.gs'
prompt 'Enter the variable to plot: '
pull cvar
'define var1=ave('cvar%',t=1,t=7)'
'define var2=ave('cvar%'.2,t=1,t=7)'
'set gxout shaded'
'd var1-var2'
'cbarn'
'set gxout contour'
'set black -.1 .1'
'd var1-var2'

