include(${CMAKE_CURRENT_LIST_DIR}/platforms/WCOSS.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/platforms/WCOSS-Cray.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/platforms/S4.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/platforms/Theia.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/platforms/Cheyenne.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/platforms/Generic.cmake)
