# $Id: Makefile,v 1.2 1998/10/02 17:34:41 davis Exp $
#
#	Makefile for netcdf man
#

include ../macros.make

PACKING_LIST	= Makefile	\
		  netcdf.m4

all:

test:

install:

uninstall:

include ../rules.make
