#!/bin/sh
# 2008
# rzdmftp_any  [SOURCE_IBM__path  extra_target_dir_name target_machine_files machine_name]
# defaulting to:
# rzdmftp_any   file_directory   rzdm_target    *.gif   username  rzdm     
#   
#   add optionally an extra_target_path to be appended to default
#   and it does not have to exist as a directory already.
#example: 
# /global/save/wx23ja/script/rzdmftp /gpfstmp/wx23ja/grads
# works to send all gif files to rzdm in directory mb.  That is, 
# /home/people/emc/www/htdocs/gmb/wd23ja/mb
#

export VERBOSE=${VERBOSE:-"YES"}

if [[ "$VERBOSE" = "YES" ]]
then
   echo $(date) EXECUTING $0 $* >&2
   set -x
fi


#
#  which directory

#IBM_directory=${1:-/global/save/wx23dc}
target_path_default=/home/people/emc/www/htdocs/gmb/dcarlis
work_dir=$1
cd $work_dir
extra_target_path=$2
target_path=${target_path_default}/${extra_target_path}
####################################################export machine_name=${3:-"rzdm"}
export machine_files=${3:-"*.gif"}
export user=${4:-"wx23dc"}
export machine_name=${5:-"rzdm"}
echo $machine_name
echo $target_path
echo $machine_files

# filelist=`ls ${machine_files}*`
# for  file in $filelist
# do
# sleep 2
# echo " ready to start another file: $file "
###ftp -n $machine_name << EOF 
###user wd23ja s,!h2cP

sftp $user@$machine_name <<EOF
mkdir $target_path
cd $target_path
put $machine_files
bye
EOF


# done
#
echo " ***** finish summary "
echo " ***** ftp to  $machine_name"
echo " ***** sent to dir  $target_path "
echo " ***** files sent to $machine_files "
date
exit
