#!/bin/csh -x

#
set Basedir = /discover/nobackup/projects/gmao/share/dao_ops/Baselibs/v3.2.0_build3
set GEOSDAS = /home/dao_ops/GEOSadas-5_13_1_sp3/GEOSadas/
set GEOSDAS = /home/dao_ops/GEOSadas-5_17/GEOSadas/
#set BufrLib = /discover/nobackup/jjin3/G590_jj/GEOSadas-5_9_1_p2_cloud/Linux/lib/libNCEP_bufr_r8i4.a
# set BufrLib = /discover/nobackup/jjin3/geos_adas/GEOSadas/Linux/lib/libNCEP_bufr_r8i4.a
# set BufrLib = /gpfsm/dhome/dao_ops/GEOSdas-2_1_4/GEOSadas/Linux/lib
# set BufrLib = /gpfsm/dhome/dao_ops/GEOSdas-2_1_4-m3/GEOSadas/Linux/lib/libNCEP_bufr_r8i4.a

set BufrLib = ${GEOSDAS}/Linux/lib/libNCEP_bufr_r8i4.a
#set HDFincdir  = /usr/local/other/SLES11/hdf5/1.8.7/intel-11.1.038/include
#set HDFlibdir  = /usr/local/other/SLES11/hdf5/1.8.7/intel-11.1.038/lib
set HDFincdir  = $Basedir/Linux/include/hdf5
set HDFlibdir  = $Basedir/Linux/lib

set _Ihdf5 = "-I$HDFincdir"
#set _Lhdf5 = "-lhdf5_fortran"
#set _Lhdf5 = "-lhdf5_hl"


#
#
ifort -c $_Ihdf5 gmi1cr_hdf2bufr.f90  \
                 hdf5rd_mod.f90 \
                 wr_gmi_bufr_1cr.f90 \
                 ymd_thhz.f90 \
                 ymdhms2tim13.f90 
#----------------------------------------------------------------
ifort -o gmi1cr_bufr.x gmi1cr_hdf2bufr.o  \
         hdf5rd_mod.o \
         wr_gmi_bufr_1cr.o \
         ymd_thhz.o  \
         ymdhms2tim13.o \
      -L/$Basedir/Linux/lib/ \
	-lnetcdf \
	-lhdf5_hl \
	-lhdf5_fortran \
	-lhdf5 \
	-lz -lmfhdf -ldf -lsz -ljpeg -lcurl -lrt $BufrLib

#
/bin/rm -f *.o
